# Generated by Django 5.0.6 on 2024-05-09 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryexpense',
            unique_together={('user', 'name')},
        ),
    ]
